### ISSUE TITLE
chayns.setSubTapp(config) misbehavior

### ISSUE THREAD

**Issue by meldau** [TobitSoftware/chayns-js#5]
This function creates a tapp, but not in the way it is documented:
- **name**: it is shown in _uppercase_ and with a _trailing exclamation mark_. Both is unexpected and disruptive
- **color** _doesn't change_, no matter if color or colorText is used
- **isExclusiveView**: Tapp opens in _normal view_, no matter if set to true or false
- **buttonName** should "name" the navigation button but is _not used_ anywhere
- **boldText**: does not work, too

Above is behavior on Desktop.
On Android  **name** is empty and **position** is always between "Support" and "Zubehör", no matter what **sortID** wanna force...

**Comment by SteffenHo** [comment]
Hello meldau, 

Thank you for your Issue. We are sorry for your problems with chayns.setSubTapp(config). 
At the moment we are fixing the problems.

**IOS-App**
The problems with the "isExclusiveView" are fixed in version 5.559 or heigher

**Android - App**
The parameters "Name", "Icon"  "SortID" and "buttonName" are heeded in appversion 5.489 or heigher.

**Web**
ReplaceParent: false and a url without TappID work correct now.


**Further Problems**

Color must a hexvalue with 8 letters e.g. #CCFFFF00.  The first two letters define the opacity. The ChaynsWeb will fix it and than Hex with 6 letters are possible. 

The problem with uppercase and the '!' will be fixed in the chaynsApi next week.

Greetings
SteffenHo

**Comment by meldau** [comment]
Hello SteffenHo,
I can only test within browsers until app updates are out. 
Color and text issues are fixed, thx so far. But on web **boldText** and **isExclusiveView** are still out of order.

**Comment by SteffenHo** [comment]
Hello meldau,

We are still working on your issues. You are right, the parameter **isExclusiveView** has still a problem but the name in our navigation is written with bold letters, if you set **boldText** true.

```javascript
chayns.setSubTapp({
 'tappID': 76544,
 'url': 'http://developers.chayns.net/FrontendSnippets',
 'name': 'Snippets-Subtapp',
 'color': '#ffff00',
 'sortID': 8989,
 'icon': 'fa-plus',
 'buttonName': 'Button',
 'replaceParent': true,
 'boldText': true
});
```

**Comment by meldau** [comment]
nope, not at my test - boldText:true doesn't change a thing:
`<a class="AjaxLink" style="display: block" onclick="customTapp.loadUrl('https://a...', 476246); window.ChaynsInfo.Tapps.push({'ExclusiveMode': false, 'Id': '476246', 'InternalName': 'SubTapp476246', 'ShowName': 'Sub Tapp', 'Url': 'https://a....'})" id="setEvt-9377222560838526"><div class="NavItemBadge"></div><div class="NavItem active" style="color: rgba(255,0,0, 1) !important;" data-tappid="476246" data-sortid="100"><span class="NavSymbol ChaynsCS-Color-75Pcnt fa fa-plus" style="color: rgba(255,0,0, 1) !important;"></span>Sub Tapp</div></a>
<a class="AjaxLink" style="display: block" onclick="customTapp.loadUrl('https://a...', 476246); window.ChaynsInfo.Tapps.push({'ExclusiveMode': false, 'Id': '476246', 'InternalName': 'SubTapp476246', 'ShowName': 'Sub Tapp', 'Url': 'https://a....'})" id="setEvt-9377222560838526"><div class="NavItemBadge"></div><div class="NavItem active" style="color: rgba(255,0,0, 1) !important;" data-tappid="476246" data-sortid="100"><span class="NavSymbol ChaynsCS-Color-75Pcnt fa fa-plus" style="color: rgba(255,0,0, 1) !important;"></span>Sub Tapp</div></a>`

tested with `"boldText":true,` and  `"boldText": 1,`


compared to your own "Kaufen"-Button after clicking on primesite the element style is missing: 
`<a class="AjaxLink AdminLink" href="/tapp/index/100206159" id="setEvt-15835735318484878">
	<div class="NavItemBadge"></div>
	<div class="NavItem SingleTapp active" data-tappid="100206159" data-sortid="-2000" data-issubtapp="1" style="`**font-weight: bold;**` color: rgb(210, 63, 49);">
		<span class="NavSymbol ChaynsCS-Color-75Pcnt fa ts-badge" style="color: rgb(210, 63, 49);"></span>KAUFEN!</div>
</a>`

**Comment by SteffenHo** [comment]
Could you please give us exactly the call you are calling?

**Comment by meldau** [comment]
sure, here it is: 
```
chayns.setSubTapp({
	"tappID": 483665,"url": "https://ap.../?sid=....TobitAccessToken=ew..Q", "name": "Sub Tapp",
"boldText": true,
					 "xcolor": "#FFf000","colorText":"#ffff0000",
					 "sortID": 100,
					 "icon": "fa-plus",
"buttonName": "subtapp1",
"isExclusiveView":true,
					 "replaceParent": false
				});
```

**Comment by meldau** [comment]
Sorry, but now I cannot even click the created Tapp. Wonder why??
console: `ReferenceError: loadUrl is not defined` on desktop browser

**Comment by meldau** [comment]
meanwhile app updates are out but desktop still running in `ReferenceError: loadUrl is not defined` error when clicking the created menu item.
what do you think how long do you need to fix that problem, @SteffenHo ?

**Comment by meldau** [comment]
anything new, @SteffenHo @uvalmsick ??? The problem is getting worse since SubTapp() is not usable at all, because of not opening on WebShadow. Clients are waiting more than a month now. So please, solve the bugs so I can use this function again properly.

**Comment by uvalmsick** [comment]
Hi @meldau, thank for you request. You Issue is under investigation. We contact you as soon as possible

**Comment by SteffenHo** [comment]
Hello @meldau 

We implemented your usage of the call in ChaynsWeb and now you can use the call in the way you want. 

```js
chayns.setSubTapp({
   "tappID": 483665,
   "url": "https://bamboo-ahaus.de/Bestellen", 
   "name": "Sub Tapp",
   "boldText": true,
   "color": "#FFf000",
   "colorText":"#ffff0000",
   "sortID": 100,
   "icon": "fa-plus",
   "buttonName": "subtapp1",
   "isExclusiveView":true,
   "replaceParent": false
});
```

**Comment by meldau** [comment]
That's great, thanks a lot!!!
